name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # 変更を監視するブランチを指定

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
      LAYER_NAME: ${{ secrets.LAMBDA_LAYER_NAME }}
      LAYER_ARN: ${{ secrets.LAMBDA_LAYER_ARN }}
      LAYER_ZIP: layer.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Zip Lambda function
      run: zip -j function.zip index.mjs

    - name: Package Lambda Layer
      run: |
        mkdir -p layer/nodejs
        cp -r node_modules layer/nodejs/
        zip -r ${LAYER_ZIP} layer

    - name: Configure AWS credentials  # AWS認証情報を設定
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda Layer
      run: aws lambda publish-layer-version --layer-name ${{ env.LAYER_NAME }} --zip-file fileb://${{ env.LAYER_ZIP }} --compatible-runtimes nodejs14.x
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # 必要に応じてリージョンを設定
  
    - name: Deploy to AWS Lambda
      run: aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # 必要に応じてリージョンを設定

    - name: Get latest layer version
      id: layer_version
      run: |
        LAYER_VERSION=$(aws lambda list-layer-versions --layer-name ${{ env.LAYER_NAME }} --query 'LayerVersions[0].Version' --output text)
        echo "LAYER_VERSION=$LAYER_VERSION" >> $GITHUB_ENV
      
    - name: Wait for previous update to complete
      run: sleep 30

    - name: Update Lambda Function with New Layer Version
      run: aws lambda update-function-configuration --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --layers ${{ env.LAYER_ARN }}:${{ env.LAYER_VERSION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # 必要に応じてリージョンを設定
        LAYER_VERSION: ${{ env.LAYER_VERSION }}